### ISSUE TITLE
Mejora en la seguridad del bot

### ISSUE THREAD

**Issue by jagarciavi** [ACM-USAL/acm-sig-bot#14]
El bot debería comprobar antes de mandar el típico mensaje "Hey talytal ha solicitado entrar en el grupo! :)" si el usuario se encuentra en ACM-Offtopic o en ACM-USAL. Otro detalle es que si se añade el bot a otro grupo que no pertenece a ACM, el bot no debería funcionar en ese grupo.

**Comment by hectorgoan** [comment]
Gente, yo no he participado nada en el bot, pero estáis haciendo un trabajo genial!
