### ISSUE TITLE
[Idea] Añadir que el Bot mande los mensajes por DM

### ISSUE THREAD

**Issue by ganchito55** [ACM-USAL/acm-sig-bot#6]
Estaría bien para no inundar el grupo que el bot mande los mensajes por un chat propio con el interesado.

Según la API:
sendMessage

Use this method to send text messages. On success, the sent Message is returned.
Parameters 	Type 	Required 	Description
chat_id 	Integer 	Yes 	Unique identifier for the message recipient — User or GroupChat id

Con tener el User ID y cambiarlo en lugar del chatID valdría, pero ando algo verde en esto.

**Comment by ecoal95** [comment]
Cerrando esto porque dichos mensajes no llegarán si la persona no ha hablado con el bot en privado.
