### ISSUE TITLE
Mejorar el comportamiento del bot cuando hay más de una pregunta nueva en ACM respuestas

### ISSUE THREAD

**Issue by ecoal95** [ACM-USAL/acm-sig-bot#8]
El bot ahora itera por todas las preguntas nuevas y manda tantos mensajes como preguntas haya.

Es muy infrecuente que haya más de una pregunta cada cinco minutos, pero puede pasar.

Sería mucho mejor si cuando hubiera más de una pregunta nueva se mandara un mensaje más genérico, o sólo se mandara un mensaje a secas, al estilo:

> Hay {n} pregunta(s) nuevas en ACM respuestas:
>  - Título 1 (url 1)
> ...
>  - Título n (url n)

Esta puede ser una buena issue para el taller de git.

Código relevante:
https://github.com/ACM-USAL/acm-sig-bot/blob/master/index.js#L231

**Comment by Alternhuman** [comment]
Me parece buena idea meterlo en el taller :)
